"""initial schema

Revision ID: 21b5f0c5df5b
Revises: 
Create Date: 2026-02-15 14:17:25.189334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b5f0c5df5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memos',
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('file_hash'),
    sa.UniqueConstraint('file_id')
    )
    op.create_table('transcriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('memo_hash', sa.String(), nullable=False),
    sa.Column('transcribed_at', sa.DateTime(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['memo_hash'], ['memos.file_hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcriptions')
    op.drop_table('memos')
    # ### end Alembic commands ###
